version: '2'

services:
  php56:
    build:
      context: .
      dockerfile: Dockerfile.php56
    volumes:
      - ./.php56/composer.json:/opt/phing-commons/composer.json
      - ./.php56/composer.lock:/opt/phing-commons/composer.lock
      - ./.php56/bin:/opt/phing-commons/bin
      - ./.php56/vendor:/opt/phing-commons/vendor

  php70:
    build:
      context: .
      dockerfile: Dockerfile.php70
    volumes:
      - ./.releases:/releases

  php71:
    build:
      context: .
      dockerfile: Dockerfile.php71
    volumes:
      - ./.releases:/releases