#!/bin/sh

while [ $# -gt 0 ]; do
    arg=$1

    case $arg in
        start)
            docker-compose up --build -d
        ;;
        stop)
            docker-compose stop
        ;;
        update)
            docker-compose run php56 bash -c 'cd /opt/phing-commons; composer update'
            docker-compose run php70 bash -c 'cd /opt/phing-commons; composer update'
            docker-compose run php71 bash -c 'cd /opt/phing-commons; composer update'
        ;;
        *)
            echo ""
            echo "commands:"
            echo ""
            echo "./docker start"
            echo "./docker stop"
            echo "./docker update"
            echo ""
        ;;
    esac
    shift
done