version: '2'

services:
  php56:
    build:
      context: .
      dockerfile: Dockerfile.php56

  php70:
    build:
      context: .
      dockerfile: Dockerfile.php70

  php71:
    build:
      context: .
      dockerfile: Dockerfile.php71