version: '2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # phing commons main files
      - ./commons:/opt/phing-commons/commons
      - ./resources:/opt/phing-commons/resources
      - ./src:/opt/phing-commons/src
      - ./tests:/opt/phing-commons/tests
      - ./build.properties:/opt/phing-commons/build.properties
      - ./build.xml:/opt/phing-commons/build.xml
      - ./composer.json:/opt/phing-commons/composer.json
      - ./phpunit.xml:/opt/phing-commons/phpunit.xml
      - ./VERSION:/opt/phing-commons/VERSION

      # phing commons composer
      - ./vendor:/opt/phing-commons/vendor
      - ./composer.lock:/opt/phing-commons/composer.lock