version: '2'

services:
  php56:
    build:
      context: .
      dockerfile: Dockerfile.php56
    volumes:
      - ./.releases:/releases

  php70:
    build:
      context: .
      dockerfile: Dockerfile.php70
    volumes:
      - ./.releases:/releases

  php71:
    build:
      context: .
      dockerfile: Dockerfile.php71
    volumes:
      - ./.releases:/releases