version: '2'

services:
  php56:
    build:
      context: .
      dockerfile: Dockerfile.php56
    environment:
      - COMPOSER_GITHUB_OAUTH_TOKEN=your-github-oauth-token
    volumes:
    volumes:
      - ./vendor-php56:/opt/phing-commons/vendor
      - ./composer.lock.php56:/opt/phing-commons/composer.lock

  php70:
    build:
      context: .
      dockerfile: Dockerfile.php70
    environment:
      - COMPOSER_GITHUB_OAUTH_TOKEN=your-github-oauth-token
    volumes:
      - ./vendor-php70:/opt/phing-commons/vendor
      - ./composer.lock.php70:/opt/phing-commons/composer.lock

  php71:
    build:
      context: .
      dockerfile: Dockerfile.php71
    environment:
      - COMPOSER_GITHUB_OAUTH_TOKEN=your-github-oauth-token
    volumes:
      - ./vendor-php71:/opt/phing-commons/vendor
      - ./composer.lock.php71:/opt/phing-commons/composer.lock