version: '2'

services:
  php56:
    build:
      context: .
      dockerfile: Dockerfile.php56
    volumes:
      - ./.php56/composer.lock:/opt/phing-commons/composer.lock
      - ./.php56/bin:/opt/phing-commons/bin
      - ./.php56/vendor:/opt/phing-commons/vendor
      - ./commons:/opt/phing-commons/commons
      - ./resources:/opt/phing-commons/resources
      - ./src:/opt/phing-commons/src
      - ./build.properties:/opt/phing-commons/build.properties
      - ./build.xml:/opt/phing-commons/build.xml
      - ./composer.json:/opt/phing-commons/composer.json
      - ./VERSION:/opt/phing-commons/VERSION

  php70:
    build:
      context: .
      dockerfile: Dockerfile.php70
    volumes:
      - ./.php70/composer.lock:/opt/phing-commons/composer.lock
      - ./.php70/bin:/opt/phing-commons/bin
      - ./.php70/vendor:/opt/phing-commons/vendor
      - ./commons:/opt/phing-commons/commons
      - ./resources:/opt/phing-commons/resources
      - ./src:/opt/phing-commons/src
      - ./build.properties:/opt/phing-commons/build.properties
      - ./build.xml:/opt/phing-commons/build.xml
      - ./composer.json:/opt/phing-commons/composer.json
      - ./VERSION:/opt/phing-commons/VERSION

  php71:
    build:
      context: .
      dockerfile: Dockerfile.php71
    volumes:
      - ./.php71/composer.lock:/opt/phing-commons/composer.lock
      - ./.php71/bin:/opt/phing-commons/bin
      - ./.php71/vendor:/opt/phing-commons/vendor
      - ./commons:/opt/phing-commons/commons
      - ./resources:/opt/phing-commons/resources
      - ./src:/opt/phing-commons/src
      - ./build.properties:/opt/phing-commons/build.properties
      - ./build.xml:/opt/phing-commons/build.xml
      - ./composer.json:/opt/phing-commons/composer.json
      - ./VERSION:/opt/phing-commons/VERSION