#!/bin/sh

docker pull elnebuloso/phing-commons:php56-latest \
&& docker run --name phing-commons-php56 -d elnebuloso/phing-commons:php56-latest

docker pull elnebuloso/phing-commons:php70-latest \
&& docker run --name phing-commons-php70 -d elnebuloso/phing-commons:php70-latest

docker pull elnebuloso/phing-commons:php71-latest \
&& docker run --name phing-commons-php71 -d elnebuloso/phing-commons:php71-latest